spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3303/apidb
    username: apidbuser
    password: apidbuser
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true

  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 10MB

my:
  upload:
    path: upload


#logging:
#  level:
#    org:
#      hibernate:
#        sql: debug
logging:
  level:
    org:
      springframework:
        security:
          web: trace
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/mallapi